CREATE DATABASE IF NOT EXISTS SXC;

USE SXC;

CREATE TABLE EMPLOYEE (
  EID INT AUTO_INCREMENT NOT NULL,
  FirstName VARCHAR(15) NOT NULL,
  LastName VARCHAR(15) NOT NULL,
  DeptID SMALLINT,
  DOB DATE,
  PRIMARY KEY (EID)
);
SHOW VARIABLES LIKE 'datadir';
DESCRIBE EMPLOYEE;

USE SXC;
ALTER TABLE EMPLOYEE
ADD ContactNo BIGINT NOT NULL,
ADD Email VARCHAR(30) NOT NULL,
ADD Salary Decimal(10,2);

DESCRIBE EMPLOYEE;

USE SXC;

ALTER TABLE EMPLOYEE 
DROP COLUMN DOB;

USE SXC;

CREATE TABLE DEPARTMENT (
    DID SMALLINT NOT NULL,
    DName VARCHAR(20) NOT NULL,
    Email VARCHAR(20) NOT NULL,
    PRIMARY KEY (DID)
);

DESCRIBE DEPARTMENT;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT
FOREIGN KEY (DeptID)
  REFERENCES DEPARTMENT(DID);

DESCRIBE EMPLOYEE

CREATE TABLE CUSTOMER (
    CustomerID INT NOT NULL,
    CustomerName VARCHAR(50) NOT NULL,
    PRIMARY KEY (CustomerID)
);
DESCRIBE CUSTOMER;

CREATE TABLE ORDERS (
    OrderID INT NOT NULL,
    ProductName VARCHAR(50) NOT NULL,
    CustomerID INT NOT NULL,
    PRIMARY KEY (OrderID),
    FOREIGN KEY (CustomerID)
        REFERENCES Customer(CustomerID)
);

DESCRIBE ORDERS;